# coding: utf-8

# flake8: noqa

"""
    Ma super messagerie

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.body import Body
from swagger_client.models.message import Message
from swagger_client.models.reaction_emoji import ReactionEmoji
from swagger_client.models.utilisateur import Utilisateur
