# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.reaction_emoji import ReactionEmoji  # noqa: F401,E501
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, emoji: ReactionEmoji=None, message_id: int=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param emoji: The emoji of this Body.  # noqa: E501
        :type emoji: ReactionEmoji
        :param message_id: The message_id of this Body.  # noqa: E501
        :type message_id: int
        """
        self.swagger_types = {
            'emoji': ReactionEmoji,
            'message_id': int
        }

        self.attribute_map = {
            'emoji': 'emoji',
            'message_id': 'messageId'
        }
        self._emoji = emoji
        self._message_id = message_id

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def emoji(self) -> ReactionEmoji:
        """Gets the emoji of this Body.


        :return: The emoji of this Body.
        :rtype: ReactionEmoji
        """
        return self._emoji

    @emoji.setter
    def emoji(self, emoji: ReactionEmoji):
        """Sets the emoji of this Body.


        :param emoji: The emoji of this Body.
        :type emoji: ReactionEmoji
        """

        self._emoji = emoji

    @property
    def message_id(self) -> int:
        """Gets the message_id of this Body.

        Identifiant du message  # noqa: E501

        :return: The message_id of this Body.
        :rtype: int
        """
        return self._message_id

    @message_id.setter
    def message_id(self, message_id: int):
        """Sets the message_id of this Body.

        Identifiant du message  # noqa: E501

        :param message_id: The message_id of this Body.
        :type message_id: int
        """

        self._message_id = message_id
