# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Message(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, emetteur: str=None, contenu: str=None):  # noqa: E501
        """Message - a model defined in Swagger

        :param id: The id of this Message.  # noqa: E501
        :type id: int
        :param emetteur: The emetteur of this Message.  # noqa: E501
        :type emetteur: str
        :param contenu: The contenu of this Message.  # noqa: E501
        :type contenu: str
        """
        self.swagger_types = {
            'id': int,
            'emetteur': str,
            'contenu': str
        }

        self.attribute_map = {
            'id': 'id',
            'emetteur': 'emetteur',
            'contenu': 'contenu'
        }
        self._id = id
        self._emetteur = emetteur
        self._contenu = contenu

    @classmethod
    def from_dict(cls, dikt) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The message of this Message.  # noqa: E501
        :rtype: Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Message.

        Identifiant (unique) du message  # noqa: E501

        :return: The id of this Message.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Message.

        Identifiant (unique) du message  # noqa: E501

        :param id: The id of this Message.
        :type id: int
        """

        self._id = id

    @property
    def emetteur(self) -> str:
        """Gets the emetteur of this Message.

        Pseudo de l'emetteur du message  # noqa: E501

        :return: The emetteur of this Message.
        :rtype: str
        """
        return self._emetteur

    @emetteur.setter
    def emetteur(self, emetteur: str):
        """Sets the emetteur of this Message.

        Pseudo de l'emetteur du message  # noqa: E501

        :param emetteur: The emetteur of this Message.
        :type emetteur: str
        """

        self._emetteur = emetteur

    @property
    def contenu(self) -> str:
        """Gets the contenu of this Message.

        Contenu du message  # noqa: E501

        :return: The contenu of this Message.
        :rtype: str
        """
        return self._contenu

    @contenu.setter
    def contenu(self, contenu: str):
        """Sets the contenu of this Message.

        Contenu du message  # noqa: E501

        :param contenu: The contenu of this Message.
        :type contenu: str
        """

        self._contenu = contenu
