# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Utilisateur(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pseudo: str=None, mdp: str=None):  # noqa: E501
        """Utilisateur - a model defined in Swagger

        :param pseudo: The pseudo of this Utilisateur.  # noqa: E501
        :type pseudo: str
        :param mdp: The mdp of this Utilisateur.  # noqa: E501
        :type mdp: str
        """
        self.swagger_types = {
            'pseudo': str,
            'mdp': str
        }

        self.attribute_map = {
            'pseudo': 'pseudo',
            'mdp': 'mdp'
        }
        self._pseudo = pseudo
        self._mdp = mdp

    @classmethod
    def from_dict(cls, dikt) -> 'Utilisateur':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The utilisateur of this Utilisateur.  # noqa: E501
        :rtype: Utilisateur
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pseudo(self) -> str:
        """Gets the pseudo of this Utilisateur.

        Pseudo de l'utilisateur  # noqa: E501

        :return: The pseudo of this Utilisateur.
        :rtype: str
        """
        return self._pseudo

    @pseudo.setter
    def pseudo(self, pseudo: str):
        """Sets the pseudo of this Utilisateur.

        Pseudo de l'utilisateur  # noqa: E501

        :param pseudo: The pseudo of this Utilisateur.
        :type pseudo: str
        """

        self._pseudo = pseudo

    @property
    def mdp(self) -> str:
        """Gets the mdp of this Utilisateur.

        Mot de passe de l'utilisateur  # noqa: E501

        :return: The mdp of this Utilisateur.
        :rtype: str
        """
        return self._mdp

    @mdp.setter
    def mdp(self, mdp: str):
        """Sets the mdp of this Utilisateur.

        Mot de passe de l'utilisateur  # noqa: E501

        :param mdp: The mdp of this Utilisateur.
        :type mdp: str
        """

        self._mdp = mdp
