# coding: utf-8

"""
    Ma super messagerie

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Utilisateur(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pseudo': 'str',
        'mdp': 'str'
    }

    attribute_map = {
        'pseudo': 'pseudo',
        'mdp': 'mdp'
    }

    def __init__(self, pseudo=None, mdp=None):  # noqa: E501
        """Utilisateur - a model defined in Swagger"""  # noqa: E501
        self._pseudo = None
        self._mdp = None
        self.discriminator = None
        if pseudo is not None:
            self.pseudo = pseudo
        if mdp is not None:
            self.mdp = mdp

    @property
    def pseudo(self):
        """Gets the pseudo of this Utilisateur.  # noqa: E501

        Pseudo de l'utilisateur  # noqa: E501

        :return: The pseudo of this Utilisateur.  # noqa: E501
        :rtype: str
        """
        return self._pseudo

    @pseudo.setter
    def pseudo(self, pseudo):
        """Sets the pseudo of this Utilisateur.

        Pseudo de l'utilisateur  # noqa: E501

        :param pseudo: The pseudo of this Utilisateur.  # noqa: E501
        :type: str
        """

        self._pseudo = pseudo

    @property
    def mdp(self):
        """Gets the mdp of this Utilisateur.  # noqa: E501

        Mot de passe de l'utilisateur  # noqa: E501

        :return: The mdp of this Utilisateur.  # noqa: E501
        :rtype: str
        """
        return self._mdp

    @mdp.setter
    def mdp(self, mdp):
        """Sets the mdp of this Utilisateur.

        Mot de passe de l'utilisateur  # noqa: E501

        :param mdp: The mdp of this Utilisateur.  # noqa: E501
        :type: str
        """

        self._mdp = mdp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Utilisateur, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Utilisateur):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
